[package]
name = "vulkan-bda"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ash = "0.38.0"
ash-window = "0.13.0"
bitflags = "2.5.0"
bytemuck = "1.16.0"
raw-window-handle = "0.6.2"
shaderc = "0.8.3"
winit = "0.30.1"
